services:
  backend:
    image: mikhailkuzmich/building-appraisal-app-backend:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://zero:one@mongodb:27017/buildings?authSource=admin
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_MAIL_DEVELOPER=${DEVELOPER_EMAIL}
      - FILE_UPLOAD_DIR=/app/uploads
    volumes:
      - ${FILE_UPLOAD_DIR}:/app/uploads
    depends_on:
      - mongodb

  frontend:
    image: mikhailkuzmich/building-appraisal-app-frontend:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-localhost}

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zero
      - MONGO_INITDB_ROOT_PASSWORD=one
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: