services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
      cache_from:
        - maven:3-openjdk-17
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_MAIL_DEVELOPER=${DEVELOPER_EMAIL}
      - FILE_UPLOAD_DIR=/app/uploads
    volumes:
      - /home/mikhail/appdata/buildingappraisal/feedback:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - REACT_APP_API_BASE_URL=http://localhost
      cache_from:
        - node:18-alpine
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
