services:
  backend:
    image: mikhailkuzmich/building-appraisal-app-backend:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://zero:one@mongodb:27017/buildings?authSource=admin
    depends_on:
      - mongodb

  frontend:
    image: mikhailkuzmich/building-appraisal-app-frontend:latest
    ports:
      - "80:80"  # Теперь этот контейнер будет обрабатывать HTTP запросы
    networks:
      - app-network
    depends_on:
      - backend

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zero
      - MONGO_INITDB_ROOT_PASSWORD=one
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: